#include "crc16.h"

/*
    CRC, generated by x^16 + x^2 + x + 1,
*/
uint16_t crc16(uint16_t crc0, const uint8_t* data, size_t length)
{
    uint16_t crc = crc0;

    for (size_t i = 0; i < length; i++) {
        uint16_t a = (crc >> 8) ^ data[i];
        crc = (a << 2) ^ (a << 1) ^ a ^ (crc << 8);
    }

    return crc;
}
